import { type Program } from './programsData';

export const vocationalProgramsData: Program = {
  id: "vocational",
  category: "Vocational",
  focusArea: "Technical skills, trades, practical training",
  description: "Build practical skills for immediate employment. Our vocational programs cover technical trades, crafts, and specialized skills that prepare students for hands-on careers in various industries.",
  color: "#00184dff",
  image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
  levels: [
    {
      id: "vocational-cert-1year-12th",
      level: "Certificate",
      eligibility: "12th",
      courses: [
        { id: "motor-mechanic-cert-12th", name: "Motor Mechanic", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "welding-cert-12th", name: "Welding", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "welder-cert-12th", name: "Welder", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "electrician-cert-12th", name: "Electrician", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "air-conditioning-refrigeration-cert-12th", name: "Air Conditioning & Refrigeration", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "automobile-technician-cert-12th", name: "Automobile Technician", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "diesel-mechanic-cert-12th", name: "Diesel Mechanic", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "draughtsman-civil-cert-12th", name: "Draughtsman (Civil)", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "draughtsman-mechanical-cert-12th", name: "Draughtsman (Mechanical)", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "electrical-cert-12th", name: "Electrical", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "surveyor-cert-12th", name: "Surveyor", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "library-science-cert-12th", name: "Library Science", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "fitter-cert-12th", name: "Fitter", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "motor-winding-cert-12th", name: "Motor Winding", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "printing-technology-cert-12th", name: "Printing Technology", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "wireman-cert-12th", name: "Wireman", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "plumber-cert-12th", name: "Plumber", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "carpenter-cert-12th", name: "Carpenter", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "art-craft-cert-12th", name: "Art and Craft", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "personality-development-cert-12th", name: "Personality Development", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "communication-skills-cert-12th", name: "Communication Skills", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "entrepreneurship-cert-12th", name: "Entrepreneurship", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "interior-designing-cert-12th", name: "Interior Designing", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "tailoring-cert-12th", name: "Tailoring", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "jewellery-designing-cert-12th", name: "Jewellery Designing", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "merchandising-cert-12th", name: "Merchandising", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "cooking-cert-12th", name: "Cooking", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "tourism-management-cert-12th", name: "Tourism Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "english-stenographer-cert-12th", name: "English (Stenographer)", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "hindi-stenographer-cert-12th", name: "Hindi (Stenographer)", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "librarian-cert-12th", name: "Librarian", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "english-spoken-cert-12th", name: "English Spoken", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "journalism-mass-communication-cert-12th", name: "Journalism & Mass Communication", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "retail-management-cert-12th", name: "Retail Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "hotel-management-cert-12th", name: "Hotel Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "banking-finance-cert-12th", name: "Banking & Finance", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "hospitality-management-cert-12th", name: "Hospitality Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "supply-chain-management-cert-12th", name: "Supply Chain Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "logistics-management-cert-12th", name: "Logistics Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "business-management-cert-12th", name: "Business Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "marketing-management-cert-12th", name: "Marketing Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "hospital-management-cert-12th", name: "Hospital Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "export-import-management-cert-12th", name: "Export & Import Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "financial-management-cert-12th", name: "Financial Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "operation-management-cert-12th", name: "Operation Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "physical-education-cert-12th", name: "Physical Education", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "turner-cert-12th", name: "Turner", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "taxation-cert-12th", name: "Taxation", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "social-worker-cert-12th", name: "Social Worker", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "rural-management-cert-12th", name: "Rural Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "quality-management-cert-12th", name: "Quality Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "project-management-cert-12th", name: "Project Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "office-management-cert-12th", name: "Office Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "fashion-designing-cert-12th", name: "Fashion Designing", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "mining-cert-12th", name: "Mining", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "mechanical-cert-12th", name: "Mechanical", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "mechanic-tractor-cert-12th", name: "Mechanic - Tractor", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "mechanic-diesel-cert-12th", name: "Mechanic - Diesel", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "investment-management-cert-12th", name: "Investment Management", duration: "1", durationUnit: "Year", eligibility: "12th" },
        { id: "insurance-banking-cert-12th", name: "Insurance & Banking", duration: "1", durationUnit: "Year", eligibility: "12th" }
      ]
    },
    {
      id: "vocational-diploma-2year-12th",
      level: "Diploma",
      eligibility: "12th",
      courses: [
        { id: "supply-chain-management-diploma-12th", name: "Supply Chain Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "librarian-diploma-12th", name: "Librarian", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "iti-electrician-diploma-12th", name: "ITI in Electrician", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "accountancy-diploma-12th", name: "Accountancy", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "accounting-finance-diploma-12th", name: "Accounting & Finance", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "advertising-management-diploma-12th", name: "Advertising Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "air-conditioning-refrigeration-diploma-12th", name: "Air Conditioning & Refrigeration", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "art-craft-diploma-12th", name: "Art & Craft", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "automobile-technician-diploma-12th", name: "Automobile Technician", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "banking-finance-diploma-12th", name: "Banking & Finance", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "business-management-diploma-12th", name: "Business Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "business-law-diploma-12th", name: "Business Law", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "carpenter-diploma-12th", name: "Carpenter", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "civil-diploma-12th", name: "Civil", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "civil-law-diploma-12th", name: "Civil Law", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "computer-science-diploma-12th", name: "Computer Science", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "construction-diploma-12th", name: "Construction", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "diesel-mechanic-diploma-12th", name: "Diesel Mechanic", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "disaster-management-diploma-12th", name: "Disaster Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "draughtsman-civil-diploma-12th", name: "Draughtsman (Civil)", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "draughtsman-mechanical-diploma-12th", name: "Draughtsman (Mechanical)", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "electrical-diploma-12th", name: "Electrical", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "electrical-electronics-diploma-12th", name: "Electrical & Electronics", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "electronics-communication-diploma-12th", name: "Electronics & Communication", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "entrepreneurship-diploma-12th", name: "Entrepreneurship", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "environmental-laws-diploma-12th", name: "Environmental Laws", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "environmental-science-diploma-12th", name: "Environmental Science", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "event-management-diploma-12th", name: "Event Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "export-import-management-diploma-12th", name: "Export & Import Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "fashion-designing-diploma-12th", name: "Fashion Designing", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "finance-diploma-12th", name: "Finance", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "financial-management-diploma-12th", name: "Financial Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "fine-arts-diploma-12th", name: "Fine Arts", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "fitter-diploma-12th", name: "Fitter", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "front-office-diploma-12th", name: "Front Office", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "home-science-diploma-12th", name: "Home Science", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "hospital-management-diploma-12th", name: "Hospital Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "hospitality-management-diploma-12th", name: "Hospitality Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "hospitality-tourism-diploma-12th", name: "Hospitality & Tourism", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "hotel-management-diploma-12th", name: "Hotel Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "house-keeping-diploma-12th", name: "House Keeping", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "human-resource-management-diploma-12th", name: "Human Resource Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "human-rights-law-diploma-12th", name: "Human Rights Law", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "insurance-banking-diploma-12th", name: "Insurance & Banking", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "intellectual-property-rights-diploma-12th", name: "Intellectual Property Rights", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "interior-designing-diploma-12th", name: "Interior Designing", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "international-business-management-diploma-12th", name: "International Business Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "investment-management-diploma-12th", name: "Investment Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "jewellery-designing-diploma-12th", name: "Jewellery Designing", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "journalism-mass-communication-diploma-12th", name: "Journalism & Mass Communication", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "labor-law-diploma-12th", name: "Labor Law", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "library-science-diploma-12th", name: "Library Science", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "logistics-management-diploma-12th", name: "Logistics Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "marketing-management-diploma-12th", name: "Marketing Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "material-management-diploma-12th", name: "Material Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "mechanic-diesel-diploma-12th", name: "Mechanic - Diesel", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "mechanic-tractor-diploma-12th", name: "Mechanic - Tractor", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "mechanical-diploma-12th", name: "Mechanical", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "merchandising-diploma-12th", name: "Merchandising", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "mining-diploma-12th", name: "Mining", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "motor-mechanic-diploma-12th", name: "Motor Mechanic", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "motor-winding-diploma-12th", name: "Motor Winding", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "office-management-diploma-12th", name: "Office Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "operation-management-diploma-12th", name: "Operation Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "physical-education-diploma-12th", name: "Physical Education", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "plumber-diploma-12th", name: "Plumber", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "printing-technology-diploma-12th", name: "Printing Technology", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "production-management-diploma-12th", name: "Production Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "project-management-diploma-12th", name: "Project Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "quality-management-diploma-12th", name: "Quality Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "retail-management-diploma-12th", name: "Retail Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "risk-management-diploma-12th", name: "Risk Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "rural-management-diploma-12th", name: "Rural Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "taxation-diploma-12th", name: "Taxation", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "tourism-management-diploma-12th", name: "Tourism Management", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "textile-diploma-12th", name: "Textile", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "turner-diploma-12th", name: "Turner", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "welder-diploma-12th", name: "Welder", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "welding-diploma-12th", name: "Welding", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "wireman-diploma-12th", name: "Wireman", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "electrician-diploma-12th", name: "Electrician", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "surveyor-diploma-12th", name: "Surveyor", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "iti-plumbing-diploma-12th", name: "ITI in Plumbing", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "iti-welder-diploma-12th", name: "ITI in Welder", duration: "2", durationUnit: "Year", eligibility: "12th" },
        { id: "iti-fitter-diploma-12th", name: "ITI in Fitter", duration: "2", durationUnit: "Year", eligibility: "12th" }
      ]
    },
    {
      id: "vocational-diploma-2year-10th",
      level: "Diploma",
      eligibility: "10th",
      courses: [
        { id: "supply-chain-management-diploma-10th", name: "Supply Chain Management", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "librarian-diploma-10th", name: "Librarian", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "iti-electrician-diploma-10th", name: "ITI in Electrician", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "accountancy-diploma-10th", name: "Accountancy", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "accounting-finance-diploma-10th", name: "Accounting & Finance", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "advertising-management-diploma-10th", name: "Advertising Management", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "air-conditioning-refrigeration-diploma-10th", name: "Air Conditioning & Refrigeration", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "art-craft-diploma-10th", name: "Art & Craft", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "automobile-technician-diploma-10th", name: "Automobile Technician", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "banking-finance-diploma-10th", name: "Banking & Finance", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "business-management-diploma-10th", name: "Business Management", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "business-law-diploma-10th", name: "Business Law", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "carpenter-diploma-10th", name: "Carpenter", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "civil-diploma-10th", name: "Civil", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "civil-law-diploma-10th", name: "Civil Law", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "computer-science-diploma-10th", name: "Computer Science", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "construction-diploma-10th", name: "Construction", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "diesel-mechanic-diploma-10th", name: "Diesel Mechanic", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "disaster-management-diploma-10th", name: "Disaster Management", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "draughtsman-civil-diploma-10th", name: "Draughtsman (Civil)", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "draughtsman-mechanical-diploma-10th", name: "Draughtsman (Mechanical)", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "electrical-diploma-10th", name: "Electrical", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "electrical-electronics-diploma-10th", name: "Electrical & Electronics", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "electronics-communication-diploma-10th", name: "Electronics & Communication", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "entrepreneurship-diploma-10th", name: "Entrepreneurship", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "environmental-laws-diploma-10th", name: "Environmental Laws", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "environmental-science-diploma-10th", name: "Environmental Science", duration: "2", durationUnit: "Year", eligibility: "10th" },
        { id: "event-management-diploma-10th", name: "Event Management", duration: "2", durationUnit: "Year", eligibility: "10th" }
      ]
    }
  ]
};
